-- Comprehensive Fix Table Access for Guest Users (Corrected)

-- 1. FIX WEBTOONS
ALTER TABLE public.webtoons ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Everyone can view webtoons" ON public.webtoons;
CREATE POLICY "Everyone can view webtoons" ON public.webtoons FOR SELECT USING (true);

-- 2. FIX CHAPTERS
ALTER TABLE public.chapters ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Everyone can view chapters" ON public.chapters;
CREATE POLICY "Everyone can view chapters" ON public.chapters FOR SELECT USING (true);

-- 3. FIX BANNERS (Hero Slider)
-- Ensure 'banners' table exists if not already (it should, but just in case)
CREATE TABLE IF NOT EXISTS public.banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    webtoon_id BIGINT REFERENCES public.webtoons(id) ON DELETE CASCADE,
    title TEXT,
    description TEXT,
    image_url TEXT,
    image_mobile_url TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Everyone can view banners" ON public.banners;
CREATE POLICY "Everyone can view banners" ON public.banners FOR SELECT USING (true);

-- 4. FIX HOMEPAGE SECTIONS
ALTER TABLE public.homepage_sections ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Everyone can view homepage sections" ON public.homepage_sections;
CREATE POLICY "Everyone can view homepage sections" ON public.homepage_sections FOR SELECT USING (true);

-- 5. FIX PUBLIC PROFILES (if needed for comments/author info)
DROP POLICY IF EXISTS "Everyone can view profiles" ON public.profiles;
CREATE POLICY "Everyone can view profiles" ON public.profiles FOR SELECT USING (true);

-- 6. Grant usage on schema just to be safe
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
