-- FIX PROFILE ACCESS (Complete)
-- Run this to create the missing 'reading_progress' and 'bookmarks' tables and fix policies

BEGIN;

-- 1. Create Reading Progress Table
CREATE TABLE IF NOT EXISTS public.reading_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  chapter_id BIGINT REFERENCES chapters(id) ON DELETE CASCADE,
  webtoon_id BIGINT REFERENCES webtoons(id) ON DELETE CASCADE,
  is_finished BOOLEAN DEFAULT FALSE,
  last_read_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, chapter_id)
);

-- 2. Create Bookmarks Table
CREATE TABLE IF NOT EXISTS public.bookmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    webtoon_id BIGINT REFERENCES public.webtoons(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, webtoon_id)
);

-- 3. Reading Progress Policies
ALTER TABLE reading_progress ENABLE ROW LEVEL SECURITY;

-- Drop old policies to ensure clean state
DROP POLICY IF EXISTS "Users can view own progress" ON reading_progress;
DROP POLICY IF EXISTS "Users can update own progress" ON reading_progress;
DROP POLICY IF EXISTS "Users can insert own progress" ON reading_progress;
DROP POLICY IF EXISTS "Users can manage their own progress" ON reading_progress;

-- Create comprehensive policies
CREATE POLICY "Users can view own progress" ON reading_progress
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own progress" ON reading_progress
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own progress" ON reading_progress
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own progress" ON reading_progress
    FOR DELETE USING (auth.uid() = user_id);


-- 4. Bookmarks Policies
ALTER TABLE bookmarks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own bookmarks" ON bookmarks;
DROP POLICY IF EXISTS "Users can manage own bookmarks" ON bookmarks;
DROP POLICY IF EXISTS "Users can insert their own bookmarks" ON bookmarks;
DROP POLICY IF EXISTS "Users can delete their own bookmarks" ON bookmarks;

CREATE POLICY "Users can view own bookmarks" ON bookmarks
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own bookmarks" ON bookmarks
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own bookmarks" ON bookmarks
    FOR DELETE USING (auth.uid() = user_id);

-- 5. Reload Schema
NOTIFY pgrst, 'reload schema';

COMMIT;
