-- Homepage Sections Table
CREATE TABLE IF NOT EXISTS homepage_sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('recommendations', 'new_updates', 'continue_reading', 'manual_selection', 'genre_specific', 'seasonal')),
  order_index INTEGER DEFAULT 0,
  is_visible BOOLEAN DEFAULT TRUE,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS Policies
ALTER TABLE homepage_sections ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Everyone can view homepage sections" ON homepage_sections FOR SELECT USING (true);
CREATE POLICY "Admins can manage homepage sections" ON homepage_sections FOR ALL USING ( is_admin() );

-- Seed Data (Matching current layout)
INSERT INTO homepage_sections (title, type, order_index, is_visible)
VALUES 
  ('Танд санал болгох', 'recommendations', 1, TRUE),
  ('Энэ улиралд', 'seasonal', 2, TRUE),
  ('Үргэлжлүүлэн унших', 'continue_reading', 3, TRUE),
  ('Шинээр нэмэгдсэн', 'new_updates', 4, TRUE);
