-- 1. Ensure homepage_sections table exists
CREATE TABLE IF NOT EXISTS public.homepage_sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  type TEXT NOT NULL,
  order_index INTEGER DEFAULT 0,
  is_visible BOOLEAN DEFAULT TRUE,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Reset RLS for Homepage Sections
ALTER TABLE public.homepage_sections ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Everyone can view homepage sections" ON public.homepage_sections;
CREATE POLICY "Everyone can view homepage sections" ON public.homepage_sections FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins can manage homepage sections" ON public.homepage_sections;
CREATE POLICY "Admins can manage homepage sections" ON public.homepage_sections FOR ALL USING (
  exists (select 1 from public.profiles where id = auth.uid() and is_admin = true)
);

-- 3. Populate default sections if missing
INSERT INTO public.homepage_sections (title, type, order_index, is_visible)
SELECT 'Танд санал болгох', 'recommendations', 1, TRUE
WHERE NOT EXISTS (SELECT 1 FROM public.homepage_sections WHERE type = 'recommendations');

INSERT INTO public.homepage_sections (title, type, order_index, is_visible)
SELECT 'Энэ улиралд', 'seasonal', 2, TRUE
WHERE NOT EXISTS (SELECT 1 FROM public.homepage_sections WHERE type = 'seasonal');

INSERT INTO public.homepage_sections (title, type, order_index, is_visible)
SELECT 'Үргэлжлүүлэн унших', 'continue_reading', 3, TRUE
WHERE NOT EXISTS (SELECT 1 FROM public.homepage_sections WHERE type = 'continue_reading');

INSERT INTO public.homepage_sections (title, type, order_index, is_visible)
SELECT 'Шинээр нэмэгдсэн', 'new_updates', 4, TRUE
WHERE NOT EXISTS (SELECT 1 FROM public.homepage_sections WHERE type = 'new_updates');

-- 4. Re-verify Public Access for Webtoons & Chapters (Just in case)
DROP POLICY IF EXISTS "Everyone can view webtoons" ON public.webtoons;
CREATE POLICY "Everyone can view webtoons" ON public.webtoons FOR SELECT USING (true);

DROP POLICY IF EXISTS "Everyone can view chapters" ON public.chapters;
CREATE POLICY "Everyone can view chapters" ON public.chapters FOR SELECT USING (true);

DROP POLICY IF EXISTS "Everyone can view likes" ON public.likes;
CREATE POLICY "Everyone can view likes" ON public.likes FOR SELECT USING (true);

DROP POLICY IF EXISTS "Everyone can view comments" ON public.comments;
CREATE POLICY "Everyone can view comments" ON public.comments FOR SELECT USING (true);
