-- 1. Create likes table if it doesn't exist
CREATE TABLE IF NOT EXISTS likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  chapter_id BIGINT REFERENCES chapters(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, chapter_id)
);

-- 2. Create comments table if it doesn't exist
CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  chapter_id BIGINT REFERENCES chapters(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Enable RLS
ALTER TABLE likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;

-- 4. Re-apply policies (drop first to avoid errors if they exist)
DROP POLICY IF EXISTS "Everyone can view likes" ON likes;
DROP POLICY IF EXISTS "Authenticated users can toggle likes" ON likes;
-- Note: 'FOR ALL' covers INSERT, DELETE, etc.
CREATE POLICY "Everyone can view likes" ON likes FOR SELECT USING (true);
CREATE POLICY "Authenticated users can toggle likes" ON likes FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Everyone can view comments" ON comments;
DROP POLICY IF EXISTS "Authenticated users can post comments" ON comments;
DROP POLICY IF EXISTS "Users can delete their own comments" ON comments;
CREATE POLICY "Everyone can view comments" ON comments FOR SELECT USING (true);
CREATE POLICY "Authenticated users can post comments" ON comments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own comments" ON comments FOR DELETE USING (auth.uid() = user_id);

-- 5. RELOAD SCHEMA CACHE (Critical for PGRST205 error)
NOTIFY pgrst, 'reload schema';
