-- Webtoons Table
CREATE TABLE webtoons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  author TEXT NOT NULL,
  description TEXT,
  rating DECIMAL(3, 2),
  image TEXT,
  chapter_count_label TEXT,
  is_new BOOLEAN DEFAULT FALSE,
  status TEXT DEFAULT 'Ongoing',
  genres TEXT[],
  free_chapters INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Chapters Table
CREATE TABLE chapters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  webtoon_id BIGINT REFERENCES webtoons(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  images TEXT[], -- Array of image URLs for the vertical strip
  chapter_number INTEGER,
  is_published BOOLEAN DEFAULT FALSE,
  published_at TIMESTAMPTZ DEFAULT NOW(),
  date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(webtoon_id, chapter_number)
);

-- Profiles Table (Linked to Supabase Auth)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE,
  full_name TEXT,
  avatar_url TEXT,
  is_admin BOOLEAN DEFAULT FALSE,
  is_moderator BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Bookmarks (Library)
CREATE TABLE bookmarks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  webtoon_id BIGINT REFERENCES webtoons(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, webtoon_id)
);

-- Likes Table
CREATE TABLE likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  chapter_id BIGINT REFERENCES chapters(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, chapter_id)
);

-- Comments Table
CREATE TABLE comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  chapter_id BIGINT REFERENCES chapters(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- Admin Policies for Profiles
-- Helper function to check admin status (Bypasses RLS to avoid recursion)
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid() AND is_admin = TRUE
  );
$$ LANGUAGE sql SECURITY DEFINER;

-- Admin Policies for Profiles
CREATE POLICY "Admins can view all profiles" ON profiles FOR SELECT USING (
  is_admin()
);
CREATE POLICY "Admins can update all profiles" ON profiles FOR UPDATE USING (
  is_admin()
);

ALTER TABLE bookmarks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own bookmarks" ON bookmarks FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own bookmarks" ON bookmarks FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own bookmarks" ON bookmarks FOR DELETE USING (auth.uid() = user_id);

-- Public access for webtoons and chapters
ALTER TABLE webtoons ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Everyone can view webtoons" ON webtoons FOR SELECT USING (true);
CREATE POLICY "Admins can insert webtoons" ON webtoons FOR INSERT WITH CHECK ( is_admin() );
CREATE POLICY "Admins can update webtoons" ON webtoons FOR UPDATE USING ( is_admin() );
CREATE POLICY "Admins can delete webtoons" ON webtoons FOR DELETE USING ( is_admin() );

ALTER TABLE chapters ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Everyone can view chapters" ON chapters FOR SELECT USING (true);
CREATE POLICY "Admins can insert chapters" ON chapters FOR INSERT WITH CHECK ( is_admin() );
CREATE POLICY "Admins can delete chapters" ON chapters FOR DELETE USING ( is_admin() );
CREATE POLICY "Admins can update chapters" ON chapters FOR UPDATE USING ( is_admin() );

-- Social Features Policies
ALTER TABLE likes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Everyone can view likes" ON likes FOR SELECT USING (true);
CREATE POLICY "Authenticated users can toggle likes" ON likes FOR ALL USING (auth.uid() = user_id);

ALTER TABLE comments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Everyone can view comments" ON comments FOR SELECT USING (true);
CREATE POLICY "Authenticated users can post comments" ON comments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own comments" ON comments FOR DELETE USING (auth.uid() = user_id);

-- Reading Progress Table
CREATE TABLE reading_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  chapter_id BIGINT REFERENCES chapters(id) ON DELETE CASCADE,
  webtoon_id BIGINT REFERENCES webtoons(id) ON DELETE CASCADE,
  is_finished BOOLEAN DEFAULT FALSE,
  last_read_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, chapter_id)
);

ALTER TABLE reading_progress ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own progress" ON reading_progress FOR ALL USING (auth.uid() = user_id);

-- Trigger to create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url, username)
  VALUES (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'avatar_url',
    COALESCE(
      LOWER(SPLIT_PART(new.email, '@', 1)), 
      'user_' || substr(new.id::text, 1, 8)
    ) -- Fallback to ID-based username for phone users
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
