-- Translator Affiliate Program Schema
-- Run this in your Supabase SQL Editor

-- 1. Add Translator Role to Profiles
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'is_translator') THEN
        ALTER TABLE profiles ADD COLUMN is_translator BOOLEAN DEFAULT FALSE;
    END IF;
END $$;

-- 2. Link Chapters to Translators
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'chapters' AND column_name = 'translator_id') THEN
        ALTER TABLE chapters ADD COLUMN translator_id UUID REFERENCES auth.users(id) ON DELETE SET NULL;
    END IF;
END $$;

-- 3. Translator Stats (For Performance Tracking)
CREATE TABLE IF NOT EXISTS translator_stats (
    translator_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    total_chapters_translated INTEGER DEFAULT 0,
    total_views_generated BIGINT DEFAULT 0,
    total_earnings DECIMAL(10, 2) DEFAULT 0, -- Stored in MNT
    current_balance DECIMAL(10, 2) DEFAULT 0,
    last_payout_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Payout Requests
CREATE TABLE IF NOT EXISTS translator_payouts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    translator_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    amount DECIMAL(10, 2) NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'paid')),
    bank_name TEXT,
    bank_account_number TEXT,
    bank_account_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    processed_at TIMESTAMPTZ
);

-- 5. RLS Policies

-- Enable RLS
ALTER TABLE translator_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE translator_payouts ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid conflicts
DROP POLICY IF EXISTS "Translators can view their own stats" ON translator_stats;
DROP POLICY IF EXISTS "Translators can view their own payouts" ON translator_payouts;
DROP POLICY IF EXISTS "Translators can request payouts" ON translator_payouts;

-- Translator Stats Policies
CREATE POLICY "Translators can view their own stats" ON translator_stats
    FOR SELECT USING (auth.uid() = translator_id);

-- Payout Policies
CREATE POLICY "Translators can view their own payouts" ON translator_payouts
    FOR SELECT USING (auth.uid() = translator_id);

CREATE POLICY "Translators can request payouts" ON translator_payouts
    FOR INSERT WITH CHECK (auth.uid() = translator_id);
